collections:
  pages:
    output: true

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: page

exclude:
  - README.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - ai.robots.txt/

strict_front_matter: true